fog/fog

- lib/fog/aws/parsers/storage/get_bucket_notification.rb
- lib/fog/aws/requests/storage/get_bucket_notification.rb
- lib/fog/aws/requests/storage/put_bucket_notification.rb
- lib/fog/aws/storage.rb
- tests/aws/requests/storage/bucket_tests.rb
Add support for the new s3 notifications configuration, see:
http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGETnotification.html
http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUTnotification.html
> Add support for bucket notification configuration.

- lib/fog/openstack/models/storage/file.rb
> [openstack|storage] fixes around file metadata

- lib/fog/xenserver/requests/compute/create_sr.rb
> Fix RDoc build

- lib/fog/digitalocean/examples/getting_started.md
- lib/fog/digitalocean/models/compute/server.rb
- lib/fog/digitalocean/models/compute/servers.rb
Just some stuff I noticed when using fog + DO for the first time, hopefully it helps! :smile:
> Update DigitalOcean docs

- lib/fog/fogdocker/requests/compute/container_action.rb
> Fixes "Error - undefined method 'delete' for nil:NilClass" when attempting to stop a container

- fog.gemspec
- lib/fog/ovirt/compute.rb
- lib/fog/ovirt/models/compute/template.rb
adding the version attribute for ovirt templates (templates can have the same name, with different versions)
> adding version attribute for ovirt template

- Rakefile
- bin/fog
- lib/fog/bin/clodo.rb
- lib/fog/vcloud_director/models/compute/task.rb
- tests/helper.rb
> Use Fog::Formatador

- lib/fog/vsphere/requests/compute/cloudinit_to_customspec.rb
Allows the user to specify gateway and domain suffixes through user_data. @nirvdrum
> Added extra parameters for domain suffixes and gateway, added comments

- lib/fog/openstack/requests/compute/get_hypervisor_statistics.rb
Need this for reporting on our cloud platform.
> Add endpoint for hypervisor stats.

- spec/fog/bin/atmos_spec.rb
- spec/fog/bin/baremetalcloud_spec.rb
- spec/fog/bin/bluebox_spec.rb
- spec/helpers/bin.rb
- tests/compute/helper.rb
- tests/helper.rb
An assortment of specs and test changes I found on old branches.
Support work for existing behaviours to support refactoring.
> Expanded tests

- lib/fog/openstack/compute.rb
- lib/fog/openstack/requests/compute/get_hypervisor_statistics.rb
Amends https://github.com/fog/fog/pull/3462
> Fix path and include request in catalog.

- tests/google/credentials_tests.rb
Add credentials tests to Google provider.
This fixes #3413.
> [google] Add credentials tests

- lib/fog/joyent/compute.rb
> Revert "allow self-signed certs for Joyent"

- lib/fog/glesys/compute.rb
- lib/fog/glesys/models/compute/server.rb
- lib/fog/glesys/requests/compute/edit.rb
- tests/glesys/requests/compute/helper.rb
- tests/glesys/requests/compute/server_tests.rb
Will make it possible to save chages to servers.
server = compute.servers.get(serverid)
server.memorysize = 1024
server.cpucores = 1
server.save
> [GleSYS] Add ability to persist changes on existing server

- lib/fog/ovirt/models/compute/server.rb
I have implemented this in _rbovirt_ at https://github.com/abenari/rbovirt/pull/74 and this PR implements the feature into _fog_.
> [ovirt] Implement high availability flag and priority attributes

- lib/fog/openstack/models/planning/plan.rb
- tests/openstack/models/planning/plan_tests.rb
Adds destroy, save, create and update methods to Plan
model of OpenStack Planning service.
> Adds RESTlike methods to Plan of Planning service

- lib/fog/openstack/docs/planning.md
- lib/fog/openstack/examples/planning/basics.rb
This PR adds brief docs and few examples for Planning service for OpenStack.
> Tuskar docs and examples

- lib/fog/glesys/compute.rb
- lib/fog/glesys/models/compute/ssh_key.rb
- lib/fog/glesys/models/compute/ssh_keys.rb
- lib/fog/glesys/requests/compute/ssh_key_add.rb
- lib/fog/glesys/requests/compute/ssh_key_list.rb
- lib/fog/glesys/requests/compute/ssh_key_remove.rb
- tests/glesys/requests/compute/helper.rb
- tests/glesys/requests/compute/ssh_key_tests.rb
Implements support for SSH key management in the GleSYS module as per:
https://github.com/GleSYS/API/wiki/Full-API-Documentation#sshkeyadd
> [GleSYS] add support for SSH key management

- CONTRIBUTING.md
> Move contributing guidelines from fog.io to CONTRIBUTING.md

- lib/fog/openstack/compute.rb
- lib/fog/openstack/core.rb
Adding support to request V3 tokens and provision compute using v3 keystone style auth
> Added support to request V3 tokens

- CONTRIBUTING.md
Related to—but doesn't close—#3508
> CONTRIBUTING: discuss ongoing changes, link to Roadmap in Wiki and relevant issues

- lib/fog/xenserver/compute.rb
- lib/fog/xenserver/core.rb
When authenticating towards a slave host, the error `HOST_IS_SLAVE` is returned by the slave host together with the IP address of the master host. Previously this resulted in an `InvalidLogin` exception which was hiding the actual cause. Now it results in an `HostIsSlave` exception which is then used to redirect the connection to the master host in case `:xenserver_redirect_to_master` is true.
This fix also removes the previous behaviour of doing a double login when the host is a master.
This is a breaking change since I have removed the `find_pool_master` method from the `Fog::XenServer::Connection` class. However it was not working (it invoked `authenticate` at the beginning which resulted in an `InvalidLogin` exception in case of a slave) and the official way is to let …
> [XenServer] Fix the 'redirect to master' functionality

- lib/fog/opennebula/compute.rb
- lib/fog/opennebula/models/compute/servers.rb
- lib/fog/opennebula/requests/compute/image_pool.rb
- lib/fog/opennebula/requests/compute/vm_disk_snapshot.rb
- lib/fog/opennebula/requests/compute/vm_shutdown.rb
- tests/opennebula/requests/compute/vm_disk_snapshot_test.rb
Introduces following new requests for opennebula driver:
- vm_disk_snapshot
- vm_shutdown
- image_pool
> Opennebula newrequests

- lib/fog/openstack/compute.rb
- lib/fog/openstack/core.rb
- lib/fog/openstack/network.rb
It is hard to remember odd abbreviations.
> Change openstack_prj to openstack_project

- lib/fog/dynect/models/dns/records.rb
> [dynect|dns] include SOA and NS records in response

- lib/fog/rackspace/requests/cdn_v2/update_service.rb
Our new CDN is launching on Monday. Could this please be merged before then?
> Set proper content type and clear operations after request

- lib/fog/openstack/baremetal.rb
- lib/fog/openstack/models/baremetal/node.rb
- lib/fog/openstack/requests/baremetal/set_node_power_state.rb
- lib/fog/openstack/requests/baremetal/set_node_provision_state.rb
- tests/openstack/requests/baremetal/node_tests.rb
Adds support for setting node power and provision states
> [openstack|baremetal] added support for setting node states

- lib/fog/openstack/baremetal.rb
- lib/fog/openstack/models/baremetal/node.rb
- lib/fog/openstack/requests/baremetal/set_node_maintenance.rb
- lib/fog/openstack/requests/baremetal/unset_node_maintenance.rb
- tests/openstack/requests/baremetal/node_tests.rb
Openstack Ironic maintenance mode, adding set/unset maintenance
actions.
> Openstack Ironic maintenance mode

- lib/fog/openstack/compute.rb
- lib/fog/openstack/models/compute/service.rb
- lib/fog/openstack/models/compute/services.rb
- lib/fog/openstack/requests/compute/delete_service.rb
- lib/fog/openstack/requests/compute/disable_service.rb
- lib/fog/openstack/requests/compute/disable_service_log_reason.rb
- lib/fog/openstack/requests/compute/enable_service.rb
- lib/fog/openstack/requests/compute/list_services.rb
- tests/openstack/requests/compute/service_tests.rb
OpenStack add nova service API support.
> OpenStack add nova service support

- lib/fog/vsphere/requests/compute/vm_clone.rb
> [vsphere] Fix typo in vm_clone

- lib/fog/openstack/compute.rb
- lib/fog/openstack/models/compute/aggregate.rb
- lib/fog/openstack/models/compute/aggregates.rb
- lib/fog/openstack/requests/compute/add_aggregate_host.rb
- lib/fog/openstack/requests/compute/create_aggregate.rb
- lib/fog/openstack/requests/compute/delete_aggregate.rb
- lib/fog/openstack/requests/compute/get_aggregate.rb
- lib/fog/openstack/requests/compute/list_aggregates.rb
- lib/fog/openstack/requests/compute/remove_aggregate_host.rb
- lib/fog/openstack/requests/compute/update_aggregate.rb
- lib/fog/openstack/requests/compute/update_aggregate_metadata.rb
- tests/openstack/requests/compute/aggregate_tests.rb
Adding OpenStack host aggregate support
> Adding OpenStack Host Aggregate support

- lib/fog/openstack/requests/orchestration/list_resources.rb
Minor bugs from list methods unification
> Minor bugs from list methods unification

- spec/fog/openstack/volume/volume_common_setup.yml
- spec/fog/openstack/volume/volume_crud.yml
- spec/fog/openstack/volume/volume_type_read.yml
- spec/fog/openstack/volume_spec.rb
This has some code duplication with the Fog::Identity::OpenStack::V3 spec right now. I'm going to discuss this with @dhague next week and consolidate this.
Nonetheless, I'd like to have this merged to be able to move forward with adding test coverage for #3607.
> first bits of a spec for Fog::OpenStack::Volume

- lib/fog/openstack/models/network/floating_ips.rb
- lib/fog/openstack/models/network/lb_health_monitors.rb
- lib/fog/openstack/models/network/lb_members.rb
- lib/fog/openstack/models/network/lb_pools.rb
- lib/fog/openstack/models/network/lb_vips.rb
- lib/fog/openstack/models/network/networks.rb
- lib/fog/openstack/models/network/ports.rb
- lib/fog/openstack/models/network/routers.rb
- lib/fog/openstack/models/network/security_group_rules.rb
- lib/fog/openstack/models/network/security_groups.rb
- lib/fog/openstack/models/network/subnets.rb
- lib/fog/openstack/requests/volume/list_snapshots.rb
- lib/fog/openstack/requests/volume/list_snapshots_detailed.rb
Missing summary methods under network. Missing common interface
in list_snapshots and detailed method under volume.
> OpenStack missing list unification of Network and Volume

- lib/fog/openstack/requests/compute/list_security_groups.rb
Openstack security groups list typo with elseif
> Openstack security groups list typo

- Gemfile
- lib/fog/openstack/identity_v3.rb
- lib/fog/openstack/requests/network/create_subnet.rb
- spec/fog/openstack/network/common_setup.yml
- spec/fog/openstack/network/subnets_crud.yml
- spec/fog/openstack/network_spec.rb
- spec/fog/openstack/shared_context.rb
Initially the test failed because too many params are set to nil instead of just gateway_ip (because of https://github.com/fog/fog/pull/3613) - in fact gateway_ip is the *only* parameter where a null value should be passed to OpenStack.
> [openstack] Add test for subnet creation

- lib/fog/openstack/compute.rb
- lib/fog/openstack/models/compute/availability_zone.rb
- lib/fog/openstack/models/compute/availability_zones.rb
- lib/fog/openstack/requests/compute/list_zones.rb
- lib/fog/openstack/requests/compute/list_zones_detailed.rb
- tests/openstack/requests/compute/availability_zone_tests.rb
OpenStack compute add full support of availability zones
> OpenStack compute add full support of availability zones

- lib/fog/vsphere/compute.rb
- lib/fog/vsphere/requests/compute/vm_execute.rb
Adds the ability to execute arbitrary commands on a vm.
> [vsphere] Add execute request

- lib/fog/rackspace/examples/compute_v2/create_network.rb
Fixes the comment to accurately reflect how many seconds are in five
minutes.
> Fix comment: 5mins = 300s

- lib/fog/vcloud_director/generators/compute/edge_gateway_service_configuration.rb
- tests/vcloud_director/requests/compute/edge_gateway_tests.rb
> Vcloud Director supports multiple VPN tunnels.

- lib/fog/openstack/models/volume/availability_zone.rb
- lib/fog/openstack/models/volume/availability_zones.rb
- lib/fog/openstack/requests/volume/list_zones.rb
- lib/fog/openstack/volume.rb
- tests/openstack/requests/volume/availability_zone_tests.rb
Adding OpenStack volume availability_zones
> Adding OpenStack volume availability_zones

- lib/fog/openstack/models/storage/file.rb
- tests/openstack/models/storage/file_tests.rb
I provided the functionality for the delete_at and delete_after into the OpenStack provider, since was currently missing from the project. //cc @Ladas if you've bandwidth to look at it, would be awesome.
> [openstack][Storage] Added the delete_at and delete_after flags

- tests/rackspace/requests/storage/object_tests.rb
As a continue to #3665 - three obsolete lines removed.
> Fog::Storage[:rackspace] object requests test cleanup

- lib/fog/openstack/models/orchestration/stack.rb
- lib/fog/openstack/orchestration.rb
- lib/fog/openstack/requests/orchestration/patch_stack.rb
- tests/openstack/requests/orchestration/stack_tests.rb
Openstack adding Heat Patch support
> Openstack adding Heat Patch support

- lib/fog/openstack/models/volume/volume_type.rb
- lib/fog/openstack/requests/volume/create_volume_type.rb
- lib/fog/openstack/requests/volume/delete_volume_type.rb
- lib/fog/openstack/requests/volume/get_volume_type_details.rb
- lib/fog/openstack/requests/volume/update_volume_type.rb
- lib/fog/openstack/volume.rb
- tests/openstack/requests/volume/volume_type_tests.rb
Opensopestack_volumes_manage_volume_typetack volumes adding volume type management
> Openstack volumes adding volume type management

- lib/fog/openstack/requests/compute/server_actions.rb
By issue #3702 
Fix list server action endpoint, following the doc http://developer.openstack.org/api-ref-compute-v2-ext.html#listActions
Update Mock data
> [openstack] List server actions fix

- lib/fog/digitalocean/models/compute_v2/flavors.rb
- lib/fog/digitalocean/models/compute_v2/image.rb
- lib/fog/digitalocean/models/compute_v2/images.rb
- lib/fog/digitalocean/models/compute_v2/regions.rb
- lib/fog/digitalocean/models/compute_v2/servers.rb
- lib/fog/digitalocean/models/compute_v2/ssh_keys.rb
- lib/fog/digitalocean/requests/compute_v2/convert_to_snapshot.rb
- lib/fog/digitalocean/requests/compute_v2/get_image_details.rb
- lib/fog/digitalocean/requests/compute_v2/transfer_image.rb
* Adds documentation for new V2 methods
* Add new #get method for images
> [DigitalOcean] Adds documentation and missing image #get method

- lib/fog/digitalocean/requests/compute_v2/create_ssh_key.rb
- lib/fog/digitalocean/requests/compute_v2/delete_ssh_key.rb
- lib/fog/digitalocean/requests/compute_v2/list_ssh_keys.rb
Improve these mocks to more closely match real endpoint functionality
> Digital Ocean v2 create, list, delete ssh_key mocks

- lib/fog/openstack/models/storage/file.rb
- tests/openstack/models/storage/file_tests.rb
accordingly to rackspace 4ef3a6eae4acb1b765397cadaaba5fc8230321e3
> openstack swift file: added content-encoding support

- lib/fog/vsphere/requests/compute/create_vm.rb
This PR adds the functionality to set the vmware boot order.
> [vsphere] allow setting of boot order when using api > 5.0

- lib/fog/digitalocean/models/compute_v2/ssh_key.rb
> Fix DigitalOceanV2::SshKey misplaced #save, #destroy and #update methods

- lib/fog/openstack/core.rb
Thanks to @dLobatog for highlighting this at https://github.com/fog/fog/commit/4d5287020d961e794ac279c640c69a66238c33f7#commitcomment-14475988
> [openstack] Fix for bad use of instance variables in a class method

- lib/fog/digitalocean/examples/getting_started.md
> [digitalocean] Updates Getting Started for DigitalOcean

- lib/fog/digitalocean/compute_v2.rb
- lib/fog/digitalocean/requests/compute_v2/get_image_details.rb
> Fix #3785 Missing image details for digitalocean version 2 api

- fog.gemspec
> Upgrade version of fog-vsphere to 0.4. Fixes #3784.

- lib/fog/digitalocean/models/compute_v2/server.rb
checks if the digitalocean droplet is currently locked with another operation
> Added method locked?

- lib/fog/openstack/models/volume_v2/availability_zones.rb
> OpenStack fix Cinder v2 typo

- lib/fog/openstack/compute.rb
- lib/fog/openstack/models/compute/server.rb
- lib/fog/openstack/requests/compute/evacuate_server.rb
OpenStack add server evacuate action
> OpenStack add server evacuate action

- Rakefile
Added a rake task 
General refactoring
> Added rake task to install the gem

- lib/fog/openstack/identity_v2.rb
- lib/fog/openstack/identity_v3.rb
> [openstack] Allow overriding of path matcher for Keystone

- fog.gemspec
Made cloudatcost as a seperate gem.
> Added the cloudatcost as a gem

- CONTRIBUTORS.md
- lib/fog/digitalocean/models/compute_v2/regions.rb
- lib/fog/digitalocean/requests/compute_v2/list_regions.rb
#3777 in the same way images were updated to support filtering, here's the same update for regions.
> [DigitalOcean]  Added filtering capabilities to regions request.

- lib/fog/openstack/models/compute/server.rb
And also filtering for public_ip_address
> Only Rfc1918 addresses for openstack server.private_ip_address

- lib/fog/openstack/requests/compute/create_volume.rb
get options in creating new openstack volume
> fix openstack create volume can't get options bug

- lib/fog/digitalocean/models/compute_v2/images.rb
- lib/fog/digitalocean/models/compute_v2/servers.rb
- lib/fog/digitalocean/models/compute_v2/ssh_keys.rb
- lib/fog/digitalocean/models/paging_collection.rb
Please refer to fog/fog#3825 I kinda messed up the PR.So I reopened the PR here @geemus @plribeiro3000
> Support paging for digitalocean

- lib/fog/joyent/compute.rb
> Fix default API version for Joyent

- .travis.yml
- fog.gemspec
- gemfiles/Gemfile-1.9
- gemfiles/Gemfile-2.0
- gemfiles/Gemfile-edge-1.9
- gemfiles/Gemfile-edge-2.0
Ok. Now all builds succeed to install all dependencies but we still have some broken tests but we can use #3933 for that. =)
> Fix dependency issues when building

- .travis.yml
Also test on Trusty infrastructure.
> Add 2.3 and 2.4 to test builds

- lib/fog/ovirt/compute.rb
- lib/fog/ovirt/requests/compute/activate_volume.rb
- lib/fog/ovirt/requests/compute/deactivate_volume.rb
These two calls are available in the rbovirt library, and I needed access to them.
> [ovirt] Attach ovirt activate and deactivate volume requests

- lib/fog/vcloud_director/generators/compute/edge_gateway_service_configuration.rb
add id in xml only if present. Else an id is generated from xsd generation
> add id in xml only if present
