lib/fog/bare_metal_cloud/compute.rb
This change fixes the following exception.
```
$ knife baremetalcloud list servers -x xxxx -P xxxx
[excon][WARNING] Invalid Excon request keys: :host
/Users/msamaratunga/.rvm/gems/ruby-2.1.5/gems/excon-0.42.1/lib/excon/connection.rb:356:in `validate_params'
/Users/msamaratunga/.rvm/gems/ruby-2.1.5/gems/excon-0.42.1/lib/excon/connection.rb:203:in `request'
/Users/msamaratunga/.rvm/gems/ruby-2.1.5/gems/fog-1.23.0/lib/fog/xml/sax_parser_connection.rb:35:in `request'
/Users/msamaratunga/.rvm/gems/ruby-2.1.5/gems/fog-1.23.0/lib/fog/xml/connection.rb:17:in `request'
/Users/msamaratunga/.rvm/gems/ruby-2.1.5/gems/fog-1.23.0/lib/fog/bare_metal_cloud/compute.rb:79:in `request'
/Users/msamaratunga/.rvm/gems/ruby-2.1.5/gems/fog-1.23.0/lib/fog/bare_metal_cloud/requests/compute/list_servers.rb:24:in …
```
=> Fix invalid request exception,

lib/fog/aws.rb, lib/fog/aws/service_mapper.rb, lib/fog/bin/aws.rb, spec/fog/bin/aws_spec.rb
This was triggered by #3376
This is a workaround for moving the provider specific code into `fog-aws`
whilst not cluttering the module with the "bin" behaviour.
The bin behaviour usually relates to starting `fog` from the command line
and using it interactively when having a `AWS` class seemed like a nice idea.
The `AWS` namespace should rightly be available to the AWS SDK (uses `Aws`)
so this is being deprecated however each implementation has been done
standalone.
Each top level class basically includes lookup tables between a key and the class
that should be returned.
Whilst I am working on fixing the provider/service registration in `fog-core` this
is a potential fix to put these back into the modules control.
I foresee that `lib/fog/bin/aws.rb` will disappear in 2.0 and …
=> [AWS] Move key to class mapping to separate file

lib/fog/openstack/volume.rb
When running fog in my Rails app under Ruby 2.2.0, I receive the following warning:
`.bundle/ruby/2.2.0/gems/fog-1.27.0/lib/fog/openstack/volume.rb:191: warning: duplicated key at line 196 ignored: :openstack_region`
I removed the duplicate line.
=> Remove duplicate openstack_region key

lib/fog/ovirt/compute.rb
When the ovirt user is not an admin, the client must use the "filtered_api" flag, otherwise all requests fail. Adding the ovirt_filtered_api flag will allow usage of fog with non admin ovirt credentials.
=> adding option to set ovirt to use filtered API

lib/fog/xenserver/requests/compute/create_sr.rb
This is a small copy paste fail. This line is not necessary and does not relates to the actual code/deprecation.
=> Fix small typo

lib/fog/hp/requests/storage/get_object.rb
This allows specifying a Range header, which in turn results in a 206 response status.
=> [HP|storage] Add support for headers to get_object

lib/fog/vsphere/requests/compute/vm_clone.rb
Current clone behaviour:
-network_label option not specified - VM NIC type is same as template
-network_label option specified - VM NIC type is hardcoded to VirtualE1000
After nic_type option addition:
-network_label option not specified - VM NIC type is same as template
-network_label option specified - VM NIC type defaults to VirtualE1000 (backwards compatible)
-network_label and nic_type options specified - VM NIC type is what is specified in nic_type option ie. 'nic_type' => 'VirtualVmxnet3'
=> Add nic_type option

lib/fog/vsphere/requests/compute/vm_clone.rb
fixes fog/fog#3134
We want to allow someone to not set the dest_folder option because they
might not have a desired folder structure and not care. In case they
follow common examples and use a folder called 'templates/' for templates
we don't want to create the new vm in that folder. It is better to
default to the root folder.
Conflicts:
lib/fog/vsphere/requests/compute/vm_clone.rb
=> [vsphere] new default dest_folder in vm_clone

lib/fog/vsphere/requests/compute/get_network.rb, tests/vsphere/requests/compute/get_network_tests.rb
given a name and a switch name
or just a name and whether a dvs is desired
or just a name
When you just want the first (or only) distributed virtual switch on a given cluster, you for example call `get_raw_network(name, datacenter_name, true)` This enables a network admin to choose where a new machine will be placed on the network by moving a network to a distributed virtual switch or non distributed virtual switch.
=> [vsphere] find network by name and dvswitch

lib/fog/vsphere/requests/compute/get_resource_pool.rb
This appears to be the best way to allow cloning into a chosen cluster which is not using any resource pools. Luckily the cluster is able to return a default resource pool. I have this working with vsphere 5.1 and rbvmomi 1.6.0.
The option to the vm_clone method would look like this `'resource_pool' => ['cluster5', nil]`
=> [vsphere] get resource pool without name

lib/fog/vsphere/compute.rb, lib/fog/vsphere/requests/compute/get_compute_resource.rb, lib/fog/vsphere/requests/compute/list_compute_resources.rb
@nirvdrum 
I created a new feature branch to filter out the unrelated commits. Please let me know any question.
Descriptions quoted from #1978:
This patch is to add list/get compute resources of vsphere functions to fog.
Usage:
to list all compute resources: compute.list_compute_resources
to just list effective compute resources(poweron + connected + not in maintenance state) : compute.list_compute_resources({:effective => true})
to get compute resources by name: compute.get_compute_resource('xxx.xxx.xxx.xxx')
to determine if the returned compute resource is single host, check the attribute 'isSingleHost'
Notice:
Vsphere abstracts clusters and hosts that don't belong to any cluster evenly as compute resource, so the return result may refer to either cluster or single host. If you want to …
=> [vSphere] List compute resources, orginally PR#1978

lib/fog/google/models/compute/images.rb, lib/fog/vsphere/compute.rb, lib/fog/vsphere/requests/compute/cloudinit_to_customspec.rb
this PR adds a function to parse a user_data cloudinit like string ( as could be sent from foreman) and convert it to an hash usable as customisationspec
=> cloudinit to customspec support

lib/fog/google/compute.rb, lib/fog/google/core.rb, lib/fog/google/dns.rb, lib/fog/google/monitoring.rb, lib/fog/google/sql.rb
This fixes #3413.
@erjohnso, @icco I'm not sure if P12 format is deprecated, so I didn't add any *warning* message. We can add it later if it's finally deprecated.
=> [google] Add support for JSON key format

lib/fog/openstack/docs/storage.md
If `put_object_manifest` has to be called 3 times, it is probably a problem :)
=> Remove duplicate lines from code example

lib/fog/ovirt/models/compute/volume.rb
Implement `alias` attribute for `Fog::Compute::Ovirt::Volume` class according to https://github.com/abenari/rbovirt/pull/66.
=> [ovirt] Implement alias attribute for Fog::Compute::Ovirt::Volume class

fog.gemspec
fog-core version 1.27.4 includes this bug fix:
https://github.com/fog/fog-core/commit/58556e4b1e65d2ac8dd177c531dd8a23929d39e3
Without that fix, Fog fails with:
NoMethodError:
undefined method `redisplay_progressbar' for Fog::Formatador:Class
=> Use fog-core 1.27.4 and above

lib/fog/ovirt/compute.rb
The `ovirt_filtered_api` option instructs rbovirt to use oVirt's non-admin API, so that regular users can make API calls.
=> Adds `ovirt_filtered_api` to list of recognized options for Ovirt service

lib/fog/vsphere/requests/compute/vm_clone.rb
The "gateway" field of CustomizationIPSettings (http://pubs.vmware.com/vsphere-55/topic/com.vmware.wssdk.apiref.doc/vim.vm.customization.IPSettings.html) is mentioned in vm_clone but oddly never used, and causes an error if specified.
Tested against vSphere 5.5.
=> Allow setting gateway option in CustomizationIPSettings

lib/fog/glesys/models/compute/server.rb, tests/glesys/requests/compute/helper.rb, tests/glesys/requests/compute/server_tests.rb
GleSYS has deprecated their Xen Platform and VMware is now recommended instead.
* Change the default values when creating a server to use Debian 7 64-bit on OpenVZ.
* Change the tests to create severs on OpenVZ and VMWare instead of OpenVZ and Xen.
* Update the test so they are consistent with the GleSYS API.
=> [GleSYS] Xen is deprecated use VMware instead

lib/fog/xenserver/requests/compute/create_vdi.rb
When adding deprecations in https://github.com/fog/fog/pull/3357 the request to create VDI was broked.
This changes fixes the bad logic and add support for both cases (old and new api)
which means it is backwards compatible.
See https://github.com/fog/fog/pull/3468 for more info
cc/ @kongslund
=> [Xenserver] Fix Xenserver VDI creation

lib/fog/xenserver/requests/compute/create_vdi.rb
Treat `:__sr` as a String representing an opaque reference instead of treating it as a model object of type StorageRepository.
So now when invoking `compute.vdis.create` you can either provide :storage_repository or :SR.
vdi = compute.vdis.create :name_label => 'my-disk',
:SR => sr.reference
vdi = compute.vdis.create :name_label => 'my-disk',
:storage_repository => sr
See the discussions in #3469 and #3468.
cc @plribeiro3000
=> [Xenserver] Fix Xenserver VDI creation, take two

lib/fog/ovirt/requests/compute/update_interface.rb
It seems that uderlying `OVIRT::Client#update_interface` method has evolved and the parameters of this method have been changed. Because of this, an exception is thrown whenever `Fog::Compute::Ovirt::Real#update_interface` is called. This PR amends this.
=> [ovirt] Fix update_interface method

lib/fog/dnsmadeeasy/models/dns/record.rb
domain=nil for me... but id looks good
```
dme.zones.find{ |z| z.id == 'foo.instantinfrastructure.com'}.records.find_all{|r| r.name=='foo' && r.type=='A'}.first.zone
=>   <Fog::DNS::DNSMadeEasy::Zone
id="foo.instantinfrastructure.com",
domain=nil,
gtd_enabled=nil,
nameservers=nil
>
```
=> zone.id instead of zone.domain for record.destroy

lib/fog/rackspace/models/networking_v2/security_group.rb, lib/fog/rackspace/models/networking_v2/security_group_rule.rb, lib/fog/rackspace/models/networking_v2/security_group_rules.rb, lib/fog/rackspace/models/networking_v2/security_groups.rb, lib/fog/rackspace/networking_v2.rb, lib/fog/rackspace/requests/networking_v2/create_security_group.rb, lib/fog/rackspace/requests/networking_v2/create_security_group_rule.rb, lib/fog/rackspace/requests/networking_v2/delete_security_group.rb, lib/fog/rackspace/requests/networking_v2/delete_security_group_rule.rb, lib/fog/rackspace/requests/networking_v2/list_security_group_rules.rb, lib/fog/rackspace/requests/networking_v2/list_security_groups.rb, lib/fog/rackspace/requests/networking_v2/show_security_group.rb, lib/fog/rackspace/requests/networking_v2/show_security_group_rule.rb, lib/fog/rackspace/requests/networking_v2/update_security_group.rb
This pull adds SecurityGroup and SecurityGroupRules for Neutron at Rackspace.
http://developer.openstack.org/api-ref-networking-v2.html
Tests exist in an external repo and will be merged in.
=> Rackspace Neutron Security Groups & Rules

lib/fog/glesys/compute.rb
Despite the name, the urlencode function does not actually apply URL encoding. This change fixes that.
=> [glesys] fix URL encoding of API parameter values

lib/fog/rackspace/requests/storage/get_object_https_url.rb
Ran into this error, figured I might as well fix the typo.
=> [rackspace] fix minor typo in get_object_https_url

lib/fog/google/compute.rb, lib/fog/google/models/compute/server.rb, lib/fog/google/requests/compute/start_server.rb, lib/fog/google/requests/compute/stop_server.rb
Implements the following APIs:
- https://cloud.google.com/compute/docs/reference/latest/instances/start
- https://cloud.google.com/compute/docs/reference/latest/instances/stop
=> [google|compute] Adding start_server and stop_server

lib/fog/hp/storage.rb, lib/fog/openstack/requests/storage/get_object_http_url.rb, lib/fog/openstack/requests/storage/get_object_https_url.rb, tests/helpers/mock_helper.rb
I reused working code for building URL from `lib/fog/openstack/requests/storage/get_object_https_url.rb` in `lib/fog/hp/storage.rb` to add support for port there and to keep identical interface for both `create_temp_url` methods. I have not tested hp storage, but the fixes are trivial.
=> Host and port options support for create_temp_url

lib/fog/openstack/compute.rb, lib/fog/openstack/core.rb, lib/fog/openstack/network.rb
* Splitting :openstack_domain to :openstack_userdomain and :openstack_prjdomain
* Added :openstack_tenantid which can replace authentication scope from :openstack_prjdomain + openstack_tenant to :openstack_tenantid.
=> [openstack|network,compute,core] Supporting openstack auth v3 - project/user domain

lib/fog/vsphere/compute.rb
Unfortunately rbvmomi does not support environment variables, this is the only
way how to pass debug flag in to see request/reply on the STDERR.
=> Added vsphere_debug flag for stderr debugging

lib/fog/glesys/models/compute/server.rb
This syncs the list of required and optional arguments for the server/create command with the API specification:
https://github.com/GleSYS/API/wiki/Full-API-Documentation#servercreate
=> [GleSYS] server/create: sync required and optional args with API spec

lib/fog/rackspace/docs/compute_v2.md
https://github.com/fog/fog/commit/cc4bc3cb65b9648f84a69360adb55d8bd833a7f1
This code has been here since Feb 2013, but there is no documentation for it.
=> [Rackspace|Documentation] Documenting the Networks option.

lib/fog/vcloud_director/compute.rb
If you set the path option during instantiation, the console returns an"Unrecognized argument: path warning message". 
This commit removes that warning message.
=> [vCloud Director] Fixing Unrecognized argument: path warning message

lib/fog/vcloud_director/requests/compute/instantiate_vapp_template.rb
Patch that adds the functionality of modifying the name and the storage profile of the VM's contained in the VApp template (catalog_item class) during instantiation.
As an example of use: 
options = {
vdc_id: VDC_ID, network_id: NETWORK_ID,
vms_config: [
{
href: VM_SOURCE_HREF,
storage_profile_href: STORAGE_PROFILE_HREF,
name: "My VM name"
}
]
}
catalog_item.instantiate(display_name, options)
If you do not add the vms_config the behavior is the same one than the current one. 
It is based on [this documentation](http://pubs.vmware.com/vca/index.jsp?topic=%2Fcom.vmware.vcloud.api.doc_56%2FGUID-BF9B790D-512E-4EA1-99E8-6826D4B8E6DC.html).
Regards,
Miguel
=> [vCloud Director] VM name and storage profile configuration on vApp instantiate.

lib/fog/cloudstack/models/compute/public_ip_address.rb, lib/fog/cloudstack/models/compute/public_ip_addresses.rb, lib/fog/cloudstack/requests/compute/associate_ip_address.rb, lib/fog/cloudstack/requests/compute/disable_static_nat.rb, lib/fog/cloudstack/requests/compute/disassociate_ip_address.rb, lib/fog/cloudstack/requests/compute/enable_static_nat.rb, lib/fog/cloudstack/requests/compute/list_public_ip_addresses.rb, tests/cloudstack/compute/models/public_ip_address_tests.rb, tests/cloudstack/compute/models/public_ip_addresses_tests.rb, tests/compute/helper.rb
This patch improves public_ip_address and public_ip_addresses.
* fix some attribute names
* add and remove attributes based on CloudStack API document
* fix public_ip_address#initialize arguments
* add tests for models and related requests
* allow enable/disable static nat with ```public_ip_address#server=```
=> [cloudstack|compute] Public IP Address model improvement

lib/fog/vcloud_director/compute.rb
This patch allows to set the vcloud_token as an instance attribute. This does not replace the current fog['FOG_VCLOUD_TOKEN'] approach just offers an alternative.
This makes easier to have multiple instances of Fog::Compute::VcloudDirector without mixing ENV variables.
Example of instantiation:
@fog ||= Fog::Compute::VcloudDirector.new(
vcloud_director_username:      vmware_api_username,
vcloud_director_password:      vmware_password || "not-set",
....
)
@fog.vcloud_token = token
=> [vCloud Director] Set oauth-token using an attr writer

lib/fog/openstack/requests/volume/list_snapshots.rb
This is so we can pass `all_tenants: true` to the endpoint and get a full list of snapshots for the platform.
=> Allow passing query options to snapshots endpoint.

lib/fog/openstack/compute.rb, lib/fog/openstack/models/compute/flavor.rb, lib/fog/openstack/requests/compute/create_flavor_extra_specs.rb, lib/fog/openstack/requests/compute/get_flavor_extra_specs.rb, tests/openstack/requests/compute/flavor_tests.rb
Adds support for getting and creating extra_specs for an OpenStack
flavor.
=> [openstack|compute] added support for flavor extra_specs

lib/fog/openstack/compute.rb, lib/fog/openstack/core.rb, lib/fog/openstack/network.rb
Allow project and user domains to be optional and make
openstack_project_name a valid option with no warning.
=> OpenStack allow domains to be optional fix warning

lib/fog/cloudstack/models/compute/server.rb
It seems that the `size` option is not passed to `deployVirtualMachine`. It is an option supported by CloudStack to specify the size of the data disk.
https://cloudstack.apache.org/docs/api/apidocs-4.5/user/deployVirtualMachine.html
=> [cloudstack] Allow specifying the size of DATADISK on the creation of a server

lib/fog/openstack/requests/image/list_public_images_detailed.rb
Assume at the request level that the query is encoded already.
=> Do not double encode image query

fog.gemspec
We are using Fog in our application and are trying to eliminate the verbose warnings that older versions of Excon output. Since the master branch of Fog has fog-core locked to 1.27, the locked version of Excon is too low and the bug is present. We have upgraded the fog-core dependency to 1.30 in order to upgrade Excon.
=> Upgraded fog-core to version 1.30

lib/fog/openstack/examples/compute/basics.rb
The OpenStack compute docs had params for the request layer
in a model example.  I switched it to all model.
=> Fix OpenStack compute docs

lib/fog/openstack/compute.rb, lib/fog/openstack/requests/compute/list_tenants_with_flavor_access.rb
The reference implementation's endpoint URL ends with the tenant ID,
but that's not a requirement for the service to work. I work with
software that has differently-formatted endpoint URLs that don't
contain tenant IDs at all.
Review is much appreciated.
=> Fog::OpenStack::Compute: remove assumption about endpoint URL format

lib/fog/openstack/models/volume/volume.rb, lib/fog/openstack/requests/volume/create_volume.rb
analogous to [create_server](https://github.com/fog/fog/blob/master/lib/fog/openstack/requests/compute/create_server.rb#L14) the metadata option can be also used at create_volume (see [api-ref-v1](http://developer.openstack.org/api-ref-blockstorage-v1.html#createVolume) and [api-ref-v2](http://developer.openstack.org/api-ref-blockstorage-v2.html#createVolume))
=> [openstack] create_volume: add metadata option

lib/fog/openstack/requests/network/create_port.rb, lib/fog/openstack/requests/network/get_port.rb, tests/openstack/requests/network/port_tests.rb
I want to support the specification of security group when creating a port in openstack
```
Fog::Network[:openstack].create_port(network_id, {security_groups: [uuid,uuid]})
```
=> [openstack]support security-group by create port

lib/fog/openstack/identity_v3.rb
Fixes "undefined method `credentials' for #<Fog::Identity::OpenStack::V3::Mock>" in tests.
=> include core in identity_v3 mock

lib/fog/openstack/models/network/port.rb, lib/fog/openstack/requests/network/update_port.rb
The security groups option is already there in the [create-request](https://github.com/fog/fog/blob/master/lib/fog/openstack/requests/network/create_port.rb#L13), it can also be used in the update_request (see [api-ref](http://developer.openstack.org/api-ref-networking-v2.html#updatePort)) and be shown in the related model
=> OpenStack port: add security groups to model and update request

lib/fog/openstack/models/baremetal/chassis_collection.rb, lib/fog/openstack/models/baremetal/drivers.rb, lib/fog/openstack/models/baremetal/nodes.rb, lib/fog/openstack/models/baremetal/ports.rb, lib/fog/openstack/requests/baremetal/list_chassis.rb, lib/fog/openstack/requests/baremetal/list_chassis_detailed.rb, lib/fog/openstack/requests/baremetal/list_drivers.rb, lib/fog/openstack/requests/baremetal/list_nodes.rb, lib/fog/openstack/requests/baremetal/list_nodes_detailed.rb, lib/fog/openstack/requests/baremetal/list_ports.rb, lib/fog/openstack/requests/baremetal/list_ports_detailed.rb
We need to move all list methods to unified interface, where
only Hash is passed as a first argument. The hash can have
specific fields, that will be recognized and deleted. Rest
of the Hash goes directly to request :query.
This way we can start using the list methods the same. Which
is very important for handling e.g. pagination, filtering,
etc.
All changes are made backwards compatible, with deprecation
warnings, when old interface is used.
=> OpenStack Baremetal list methods unified interface

lib/fog/openstack/models/baremetal/chassis_collection.rb, lib/fog/openstack/models/baremetal/drivers.rb, lib/fog/openstack/models/baremetal/nodes.rb, lib/fog/openstack/models/baremetal/ports.rb, lib/fog/openstack/models/compute/aggregates.rb, lib/fog/openstack/models/identity_v2/ec2_credentials.rb, lib/fog/openstack/models/identity_v2/roles.rb, lib/fog/openstack/models/identity_v2/tenants.rb, lib/fog/openstack/models/identity_v2/users.rb, lib/fog/openstack/models/identity_v3/domains.rb, lib/fog/openstack/models/identity_v3/endpoints.rb, lib/fog/openstack/models/identity_v3/groups.rb, lib/fog/openstack/models/identity_v3/os_credentials.rb, lib/fog/openstack/models/identity_v3/policies.rb, lib/fog/openstack/models/identity_v3/projects.rb, lib/fog/openstack/models/identity_v3/role_assignments.rb, lib/fog/openstack/models/identity_v3/roles.rb, lib/fog/openstack/models/identity_v3/services.rb, lib/fog/openstack/models/identity_v3/users.rb, lib/fog/openstack/requests/identity_v3/list_role_assignments.rb
Changing 'all' to 'detailed' list and adding summary method for quick
non detailed lists.
This change is backwards compatible since all method will return
more data. And the alias details methods has not been released yet.
=> OpenStack Keystone and Ironic change all to detailed list

lib/fog/openstack/models/planning/plans.rb, lib/fog/openstack/models/planning/roles.rb, lib/fog/openstack/models/storage/directories.rb, lib/fog/openstack/models/storage/files.rb, lib/fog/openstack/models/volume/volume_types.rb, lib/fog/openstack/models/volume/volumes.rb, lib/fog/openstack/requests/planning/list_plans.rb, lib/fog/openstack/requests/planning/list_roles.rb, lib/fog/openstack/requests/volume/list_volume_types.rb, lib/fog/openstack/requests/volume/list_volumes_detailed.rb, lib/fog/openstack/volume.rb
We need to move all list methods to unified interface, where
only Hash is passed as a first argument. The hash can have
specific fields, that will be recognized and deleted. Rest
of the Hash goes directly to request :query.
This way we can start using the list methods the same. Which
is very important for handling e.g. pagination, filtering,
etc.
All changes are made backwards compatible, with deprecation
warnings, when old interface is used.
=> OpenStack Cinder, Swift and Tuskar list methods unified interface

lib/fog/openstack/compute.rb, lib/fog/openstack/models/compute/addresses.rb, lib/fog/openstack/models/compute/aggregates.rb, lib/fog/openstack/models/compute/flavors.rb, lib/fog/openstack/models/compute/hosts.rb, lib/fog/openstack/models/compute/images.rb, lib/fog/openstack/models/compute/key_pairs.rb, lib/fog/openstack/models/compute/security_groups.rb, lib/fog/openstack/models/compute/servers.rb, lib/fog/openstack/models/compute/services.rb, lib/fog/openstack/models/compute/snapshots.rb, lib/fog/openstack/models/compute/volumes.rb, lib/fog/openstack/requests/compute/list_aggregates.rb, lib/fog/openstack/requests/compute/list_all_addresses.rb, lib/fog/openstack/requests/compute/list_flavors.rb, lib/fog/openstack/requests/compute/list_hosts.rb, lib/fog/openstack/requests/compute/list_key_pairs.rb, lib/fog/openstack/requests/compute/list_security_groups.rb, lib/fog/openstack/requests/compute/list_snapshots.rb, lib/fog/openstack/requests/compute/list_snapshots_detail.rb, lib/fog/openstack/requests/compute/list_volumes.rb, lib/fog/openstack/requests/compute/list_volumes_detail.rb
We need to move all list methods to unified interface, where
only Hash is passed as a first argument. The hash can have
specific fields, that will be recognized and deleted. Rest
of the Hash goes directly to request :query.
This way we can start using the list methods the same. Which
is very important for handling e.g. pagination, filtering,
etc.
All changes are made backwards compatible, with deprecation
warnings, when old interface is used.
=> OpenStack Compute list methods unified interface

lib/fog/rackspace/docs/queues.md
Example code provided doesnt work, gives:
NoMethodError: undefined method `Queues' for Fog::Rackspace:Module
adding .new makes it work.
=> add missing new method call to example

lib/fog/openstack/models/image/images.rb, lib/fog/openstack/models/orchestration/events.rb, lib/fog/openstack/models/orchestration/resources.rb, lib/fog/openstack/models/orchestration/stack.rb, lib/fog/openstack/models/orchestration/stacks.rb, lib/fog/openstack/orchestration.rb, lib/fog/openstack/requests/image/list_public_images.rb, lib/fog/openstack/requests/image/list_public_images_detailed.rb, lib/fog/openstack/requests/orchestration/list_events.rb, lib/fog/openstack/requests/orchestration/list_resource_events.rb, lib/fog/openstack/requests/orchestration/list_resource_types.rb, lib/fog/openstack/requests/orchestration/list_resources.rb, lib/fog/openstack/requests/orchestration/list_stack_data.rb, lib/fog/openstack/requests/orchestration/list_stack_data_detailed.rb, lib/fog/openstack/requests/orchestration/list_stack_events.rb, tests/openstack/requests/orchestration/stack_tests.rb
We need to move all list methods to unified interface, where
only Hash is passed as a first argument. The hash can have
specific fields, that will be recognized and deleted. Rest
of the Hash goes directly to request :query. ArgumentError
is raised when mandatory param is missing.
This way we can start using the list methods the same. Which
is very important for handling e.g. pagination, filtering,
etc.
All changes are made backwards compatible, with deprecation
warnings, when old interface is used.
=> OpenStack Glance and Heat list methods unified interface

lib/fog/rackspace/models/block_storage/snapshot.rb
Now sending the `:force` argument as per the [docs](http://developer.openstack.org/api-ref-blockstorage-v1.html#createSnapshot)
(This references #3541)
``` ruby
bs = Fog::Rackspace::BlockStorage.new
v = bs.volumes.create({size: 75, display_name: "FOO"})
...
s = bs.snapshots.create({display_name: "BAR", volume_id: v.id, force: true})
```
=> Send :force flag in Snapshot payload

lib/fog/cloudstack/models/compute/network.rb
Add support for `isdefault` field in the response from CloudStacks `listNetworks` request.
https://cloudstack.apache.org/api/apidocs-4.4/user/listNetworks.html
=> [cloudstack] Use `isdefault` in `listNetworks` response

lib/fog/openstack/requests/network/create_subnet.rb
The [docs](http://developer.openstack.org/api-ref-networking-v2.html) state that a `gateway_ip` key may be passed in with nil to represent "no gateway_ip" so that a gateway IP address isn't automatically assigned.
Discovered via: http://stackoverflow.com/questions/30930343/nil-not-turning-into-null-in-request-on-fog
=> Don't remove nil keys in OpenStack#create_subnet

lib/fog/openstack/core.rb, lib/fog/openstack/network.rb
Missing network init uri, got lost probably in cleanup in
https://github.com/fog/fog/commit/83b61986bd2787dd22dc8967f28d0c78d8752aff
=> Missing network init uri

fog.gemspec
I'm trying to add <a href="http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/vpc-classiclink.html">EC2 ClassicLink</a> support to the <a href="https://github.com/chef/knife-ec2">knife ec2</a> gem.
It seems like <a href="https://github.com/fog/fog-aws/blob/916351a3532e80a0318e766ec12bb87fa2348350/lib/fog/aws/requests/compute/attach_classic_link_vpc.rb">fog-aws already supports ClassicLink</a>, so I've <a href="https://github.com/quentindemetz/knife-ec2/tree/add_support_for_ec2_classic_link">forked knife-ec2</a> to wrap around the relevant fog method.
However, it seems that the current release of fog does not require a particular version of fog-aws, which means even the latest release of fog does not include a version of fog-aws with ClassicLink support.
Please let me know if this is the …
=> Bump fog-aws dependency

lib/fog/openstack/models/volume/volume.rb, lib/fog/openstack/requests/volume/extend_volume.rb, lib/fog/openstack/volume.rb, spec/fog/openstack/volume/volume_extend.yml, spec/fog/openstack/volume_spec.rb
I would've liked to include tests, but the mock service is not up to it.
I cannot even create a volume and retrieve it again using the same ID.
=> add extend_volume request to Fog::Volume::OpenStack

lib/fog/openstack/core.rb, lib/fog/openstack/models/collection.rb, lib/fog/openstack/models/network/floating_ips.rb, lib/fog/openstack/models/network/lb_health_monitors.rb, lib/fog/openstack/models/network/lb_members.rb, lib/fog/openstack/models/network/lb_pools.rb, lib/fog/openstack/models/network/lb_vips.rb, lib/fog/openstack/models/network/networks.rb, lib/fog/openstack/models/network/ports.rb, lib/fog/openstack/models/network/routers.rb, lib/fog/openstack/models/network/security_group_rules.rb, lib/fog/openstack/models/network/security_groups.rb, lib/fog/openstack/models/network/subnets.rb
Several parts of this patch
1. base class documents how the standard interface should look
like. This doesn't bring anything to the code, since abstract
classes are redundant in ruby, but it is nice to see what should
be the standard interface.
2. load_response method saves the whole response. Usually not
only list of records is sent. It can contain also metatada about
pagination, or other useful metadata.
=> Adding Openstack Collection base class

lib/fog/openstack/models/model.rb, lib/fog/openstack/models/storage/directory.rb, lib/fog/openstack/models/storage/file.rb
base class documents how the standard interface should look
like. This doesn't bring anything to the code, since abstract
classes are redundant in ruby, but it is nice to see what should
be the standard interface.
Base class also define the repeated methods initialize and save,
so we don't need to define them in subclasess.
project is storable to attribute, since not all results contain
project associated, it's good to to be able to store the project
used when processing the collection.
=> Openstack Model base class

lib/fog/openstack/core.rb, lib/fog/openstack/identity.rb, lib/fog/openstack/identity_v3.rb, spec/fog/openstack/identity_v3/idv3_project_hier_crud_list.yml, spec/fog/openstack/identity_v3_spec.rb, spec/fog/openstack/shared_context.rb
Also enhanced identity service to make the ID of the current user accessible as current_user_id.
Note that the returned lists are empty (even if *_as_ids calls return values) unless the calling user has a role in the projects - i.e. the only projects returned are those for which the user has a role.
=> [openstack] Add tests for subtree_as_list and parents_as_list in hierarchical projects

lib/fog/openstack/storage.rb
It seems like the value used by `Fog::Storage::OpenStack::Real` for the `@openstack_management_url` is one of the few things that is not configurable on the adapter at initialization. This PR aims to make it configurable.
When paired with a valid `:openstack_auth_token` this should make it possible for the adapter to connect to Swift immediately without authenticating with Keystone.
This is useful in situations where many containers/tenants must be accessed by many processes, as it allows for caching auth information in a local file or shared memory or even something like redis. This is valuable in scenarios where keystone might not be able to handle the barrage of authentication requests for `m processes * n tenants`.
I'm open to subclassing `Fog::Storage::OpenStack::Real` if that's …
=> Allow OpenStack storage adapter to take :openstack_management_url option

lib/fog/vsphere/requests/compute/list_vm_interfaces.rb, lib/fog/vsphere/requests/compute/vm_clone.rb
After this patch, the clone_vm accepts interfaces and volumes options, taking
interface resp. volume objects to modify the ones defined in the template.
This allows to customize all the interfaces (not just changing the
network_label on one of them), as well as increasing the size of the volumes
and adding or removing them.
=> Vsphere - customizing interfaces and disks when cloning from template

lib/fog/vsphere/requests/compute/get_virtual_machine.rb
Currently when trying to look up a template in a nested folder (e.g. "Templates/Update/New") we get a NotFound error:
```bash
/Users/asebastian/.rvm/gems/ruby-2.2.2/gems/fog-1.30.0/lib/fog/vsphere/requests/compute/get_virtual_machine.rb:28:in `get_vm_ref': Templates/Update/New/ubuntu-1204-t was not found (Fog::Compute::Vsphere::NotFound)
from /Users/asebastian/.rvm/gems/ruby-2.2.2/gems/fog-1.30.0/lib/fog/vsphere/requests/compute/get_virtual_machine.rb:7:in `get_virtual_machine'
from test_get_virtual_machine.rb:12:in `initialize'
from test_get_virtual_machine.rb:23:in `new'
from test_get_virtual_machine.rb:23:in `<main>'
```
This pull request enables a user to find a virtual machine which resides in a (deeply) nested folder.
=> [vsphere] Fix nested folders in get virtual machine

lib/fog/vsphere/requests/compute/get_resource_pool.rb
This uses the traverse method instead of find, fixing issues with nested resource pools. Fixes #3579
=> [vsphere] Use traverse to get resource pools, fixes #3579

lib/fog/linode/requests/compute/avail_datacenters.rb
Adds the Frankfurt datacenter
Adds the ABBR property which was also missing
Sample from https://api.linode.com/?api_action=avail.datacenters&api_key=...
https://gist.github.com/displague/1fa95caa6adb61b61c53
=> update Linode avail_datacenters mock results

lib/fog/vsphere/requests/compute/list_clusters.rb
Create VM failed when there was a folder between Datacenter and Clusters. This bug seemed to be a typo only.
=> [vsphere] Bug in full_path cluster attribute

lib/fog/openstack/models/compute/servers.rb, lib/fog/openstack/requests/compute/list_servers.rb, lib/fog/openstack/requests/compute/list_servers_detail.rb
Fixes that options were not passed to list_servers_detail.
Adding summary method.
Fixing how :all_tenants option behaved. It has basically
overridden all other options, so filtering and pagination
didn't work for all_tenants listing.
=> OpenStack servers list options fix

lib/fog/openstack/compute.rb, lib/fog/openstack/models/compute/server.rb, lib/fog/openstack/requests/compute/shelve_offload_server.rb, lib/fog/openstack/requests/compute/shelve_server.rb, lib/fog/openstack/requests/compute/unshelve_server.rb, tests/openstack/requests/compute/server_tests.rb
Adding actions shelve, unshelve and shelve_off_load
Testing only shelve and unshelve, since shelve offload state
can be reached automaticallt dpending on settings in
shelved_offload_time in nova.conf.
=> OpenStack compute add shelve related actions

lib/fog/openstack/models/network/subnet.rb, lib/fog/openstack/requests/network/create_subnet.rb, lib/fog/openstack/requests/network/update_subnet.rb, tests/openstack/requests/network/subnet_tests.rb
The selection of vanilla options in the subnet creation needs to be the same as in update.
Especially the `gateway_ip` is tricky (hence the special treatment beforehand), because if it is not present, then OpenStack chooses a default, if you set it to nil, it will be left empty (compare [apiref](http://developer.openstack.org/api-ref-networking-v2.html#createSubnet)). So it actually makes a difference there.
Additionally I added the `:allocation_pools`vanilla option to the subnet update, which was already present in create.
And along the way I removed some requires (probable from a copy&paste error) in the subnet model method `update`.
=> [OpenStack] subnets vanilla options fix

lib/fog/openstack/core.rb, lib/fog/openstack/models/identity_v3/project.rb, lib/fog/openstack/models/identity_v3/projects.rb, spec/fog/openstack/identity_v3/idv3_project_hier_crud_list.yml, spec/fog/openstack/identity_v3_spec.rb
For subtree_as_list and parents_as_list, set subtree and parents attributes as Array of Project instead of Array of Hash.
=> [openstack] hierarchical projects: Array of Project instead of Array of Hash.

lib/fog/openstack.rb
Otherwise we get exception with missing
Fog::Identity::OpenStack::V3
=> Add missing require of identitty v3

lib/fog/vcloud_director/models/compute/task.rb
In vCloud Air, created tasks end up in an initial state of "queued."
Fog currently treats these tasks as non_running and therefore stops
waiting for them.  Because the status is not yet successful, an
exception is raised.
I propose this change to treat a "queued" task as equivalent to
"running."
=> vCloud Director queued tasks should not count as "non_running".

lib/fog/openstack.rb, lib/fog/openstack/baremetal.rb, lib/fog/openstack/compute.rb, lib/fog/openstack/core.rb, lib/fog/openstack/identity.rb, lib/fog/openstack/identity_v2.rb, lib/fog/openstack/identity_v3.rb, lib/fog/openstack/image.rb, lib/fog/openstack/metering.rb, lib/fog/openstack/models/orchestration/events.rb, lib/fog/openstack/models/orchestration/resources.rb, lib/fog/openstack/models/orchestration/stacks.rb, lib/fog/openstack/models/orchestration/templates.rb, lib/fog/openstack/network.rb, lib/fog/openstack/orchestration.rb, lib/fog/openstack/planning.rb, lib/fog/openstack/storage.rb, lib/fog/openstack/volume.rb
cleanup of https://github.com/fog/fog/pull/3642
"I noticed, that only compute and network use the core method `initialize_identity`, which enabled this services to be used with a v3 keystone - the other did not work.
Additionally I added the v3 parameters to the recognized parameters for all services and
instead of duplicating a lot of code, I took the chance to reuse the common stuff from core."
=> [openstack] move common things among services into core

lib/fog/openstack/core.rb
In the https://github.com/fog/fog/commit/803d46791f5cfe75c99084c49519af6d63248f9b
refactoring, the unscoped token passing to credentials has
been deleted. So adding unscoped token to 2 missing places.
Plus aligning the =>, so the code is more readable
=> Openstack missing passing of unscoped_token

Rakefile, lib/fog/rackspace/requests/storage/get_object_https_url.rb, tests/rackspace/requests/storage/object_tests.rb
Hi!
Rackspace CloudFiles has some [custom options](http://docs.rackspace.com/files/api/v1/cf-devguide/content/TempURL_File_Name_Overrides-d1e213.html) for a private file's temporary URL. This update allows using both `inline` and `filename` options.
=> Rackspace temporary URL special options

lib/fog/vcloud_director/models/compute/vm_customizations.rb
This method is necessary for functions such as #reload to function on
a VM customization.  This also allows users who set and save a customization
to re-fetch it to get values such as the VM administrator password.
=> Adding #get_by_id for Fog::Compute::VcloudDirector::VmCustomizations

lib/fog/vcloud_director/generators/compute/edge_gateway_service_configuration.rb, tests/vcloud_director/requests/compute/edge_gateway_tests.rb
As with local_subnets, Vcloud-director supports
multiple peer_subnets. This is a needed feature if
you want to have multiple subnets talk
over the same VPN tunnel.
=> Cloud Director supports multiple peer subnets.

lib/fog/openstack/network.rb, lib/fog/openstack/requests/network/set_tenant.rb
Api path has been reset called the network set tenants
call authenticateby network set tenant 
https://github.com/fog/fog/blob/master/lib/fog/openstack/requests/network/set_tenant.rb#L8
reset api path by openstack core
https://github.com/fog/fog/blob/master/lib/fog/openstack/core.rb#L151
api path must be set 
https://github.com/fog/fog/blob/master/lib/fog/openstack/network.rb#L242
=> [openstack]reset api path by network model set tenant 

lib/fog/openstack/volume.rb, spec/fog/openstack/volume_spec.rb
Deprecation warnings suggest:
> [fog][DEPRECATION] Calling `OpenStack[:volume].list_snapshots(true)` is deprecated, use `.list_snapshots_detailed` instead
However, `Fog::OpenStack::Volume` does not respond to `.list_snapshots_detailed`.
Adding that to the list of requests available to the OpenStack Volume service.
Added a super-simple test to make sure the Volume service now at least responds to `list_snapshots_detailed`.
=> [OpenStack] Enable list_snapshots_detailed request

lib/fog/openstack/models/compute/server.rb, lib/fog/openstack/models/orchestration/stack.rb, lib/fog/openstack/requests/compute/list_security_groups.rb
A couple fixes to internal calls that were causing deprecation warnings.
The warnings I was seeing were:
> Calling OpenStack[:compute].list_security_groups(server_id) is deprecated, use .list_security_groups(:server_id => value) instead
And,
> Calling OpenStack[:orchestration].list_resources(stack, options) is deprecated, call .list_resources(:stack => stack) or .list_resources(:stack_name => value, :stack_id => value) instead
=> Fix deprecation warnings

fog.gemspec
allow any version less than 1.0.0
fixes #3679
=> relax dependency for fog-ecloud

fog.gemspec
Since 1.8.7 compatibility has been dropped, we no longer need to lock to
the last usable version. This should allow usage of later Rails which
require newer nokogiri versions.
=> [#3099] Remove Nokogiri constraint

lib/fog/openstack/requests/volume/get_quota_usage.rb, lib/fog/openstack/volume.rb
by the discusion in #3688 
Adding new request to get quota usage of Cinder.
Usage:
```
Fog::Volume.new(arg).get_quota_usage('21087bce688b49dbaec1a11da8105b12')
=> #<Excon::Response:0x007f9e616ebed0
@body=
"{\"quota_set\": {\"gigabytes_SAS\": {\"reserved\": 0, \"limit\": 2000, \"in_use\": 180}, \"gigabytes\": {\"reserved\": 0, \"limit\": -1, \"in_use\": 180}, \"backup_gigabytes\": {\"reserved\": 0, \"limit\": 1000, \"in_use\": 0}, \"snapshots_SAS\": {\"reserved\": 0, \"limit\": -1, \"in_use\": 4}, \"snapshots\": {\"reserved\": 0, \"limit\": 50, \"in_use\": 4}, \"volumes_SAS\": {\"reserved\": 0, \"limit\": -1, \"in_use\": 5}, \"snapshots_TRUESSD\": {\"reserved\": 0, \"limit\": -1, \"in_use\": 0}, \"volumes\": {\"reserved\": 0, \"limit\": 50, \"in_use\": 5}, \"gigabytes_TRUESSD\": …
```
=> [openstack] Add request for Cinder to get quota usage

lib/fog/vcloud_director/requests/compute/get_execute_query.rb
This change does two things:
- Changes the options passed into the request in `get_execute_query.rb` to a hash rather an array
- Bugfixes an issue where our version of the vCloud Director API is not able to correctly parse an option we are requesting. More detail is within the commit.
=> URL encoding fix for vCloud Director API

.travis.yml, gemfiles/Gemfile-ruby-1.9.3
Net::SSH 3.0 dropped support for Ruby 1.9.3 so older Rubies should
declare the dependency to avoid bundling problems.
=> Limit 1.9.3 tests to use older Net::SSH

lib/fog/linode/models/compute/kernels.rb
I'm using knife-linode which depends on fog.
And it turned out that it doesn't pay attention to kernel ID provided. It instead just selects the first kernel from kernel list response.
This pull request is to fix the issue.
=> fix linode kernel selection bug

lib/fog/vsphere/models/compute/server.rb
https://www.vmware.com/support/developer/converter-sdk/conv50_apireference/vim.vm.GuestInfo.ToolsStatus.html
Having a response of `tools_state` == `toolsOld` is ok in my opinion since tools functionality doesn't change drastically revision to revision. 
Currently vSphere will force stop your assets if your vmware tools aren't up to date (even by one small revision). This behaviour is not optimal. 
The `tools_running?` check is only used in one place, the stop command in server.rb.
=> Added case to reboot gracefully if toolsOld

lib/fog/rackspace/models/compute_v2/server.rb, lib/fog/rackspace/requests/compute_v2/create_server.rb
Currently, fog hard-codes the size of Rackspace boot volumes to 100GB. 
This commit defines the boot_volume_size attribute (100GB is kept as a default).
=> Add boot_volume_size to RS compute_v2 Server Create

lib/fog/rackspace/models/compute_v2/server.rb, lib/fog/rackspace/models/compute_v2/servers.rb, tests/rackspace/models/compute_v2/server_tests.rb
Swap the logic for `:no_passwd_lock` making it `:passwd_lock`. Per #3715, we really should make our defaults the same as Rackspace's. Because so many projects rely on the fog library, and can't all add this option to pass through, we should default to the same behaviors you'd get on vanilla Rackspace.
This change is backwards compatible, but still warns those who have explicitly set :no_passwd_lock to any specific value.
Fixes #3715. RE: #2494.
=> Ensure root user behaves like Rackspace defaults

lib/fog/opennebula/models/compute/flavor.rb, lib/fog/opennebula/requests/compute/template_pool.rb, tests/opennebula/models/compute/flavor_tests.rb
OpenNebula template may include RAW data. And if RAW data is like this:
```xml
RAW=["DATA"=>"<cpu match='exact'><model fallback='allow'>core2duo</model></cpu>", "TYPE"=>"kvm"]
```
Then current implementation replaces all '>' with ''. So output template will be:
```xml
RAW=["DATA"="<cpu match='exact'<model fallback='allow'core2duo</model</cpu", "TYPE"="kvm"]
```
And it generates an error. So i patch it to generating output like this:
```xml
RAW=["DATA"="<cpu match='exact'><model fallback='allow'>core2duo</model></cpu>", "TYPE"="kvm"]
```
=> change get_raw replacement regex from />/ to /=>/ for output XML

lib/fog/vsphere/models/compute/network.rb, lib/fog/vsphere/requests/compute/list_networks.rb, lib/fog/vsphere/requests/compute/vm_clone.rb
We were not passing the datacenter parameter when searching for networks,
which caused issues when searching for distributed switches attributes
Also, I've extracted the virtualswitch parameter to the network model,
which allows to specify the virtualswitch value for the network interface
based on the network data later. Our workflow is letting the user
to choose what network should be the nic attached to and then creating
the networks correspondingly and we use the network object for that.
=> Fix distributed port group switches support for cloning with multiple networks

lib/fog/vsphere/requests/compute/create_vm.rb
Hi, This is a fix for creating a vm with more than 7 disks. The issue exists because the SCSI controller takes ID 7, and the fog library creates disks generally based on array key (in the case of Foreman anyway). #3728
=> [vsphere] - unable to add more than 7 disks

lib/fog/openstack/models/baremetal/nodes.rb
"find_by_id" is not defined. That's a typo that should be "find_by_uuid". It causes the below error if you try to call the destroy method. This commit fixes it.
Excon::Errors::BadRequest: Expected([200, 204]) <=> Actual(400 Bad Request)
excon.error.response
:body          => "{\"error_message\": \"{\\\"debuginfo\\\": null, \\\"faultcode\\\": \\\"Client\\\", \\\"faultstring\\\": \\\"Unknown argument: \\\\\\\"id\\\\\\\"\\\"}\"}"
from /opt/rh/ruby193/root/usr/share/gems/gems/excon-0.45.3/lib/excon/middlewares/expects.rb:10:in `response_call'
from /opt/rh/ruby193/root/usr/share/gems/gems/excon-0.45.3/lib/excon/middlewares/response_parser.rb:8:in `response_call'
from /opt/rh/ruby193/root/usr/share/gems/gems/excon-0.45.3/lib/excon/connection.rb:372:in `response'
from …
=> fix method call name in openstack node destroy so that it will work

lib/fog/vsphere/compute.rb, lib/fog/vsphere/models/compute/server.rb, lib/fog/vsphere/requests/compute/vm_take_snapshot.rb, tests/helper.rb, tests/vsphere/models/compute/server_tests.rb, tests/vsphere/requests/compute/vm_take_snapshot_tests.rb
Hi,
This is the first improvement of vsphere provider for fog. It adds the ability to take snapshot only, it simply adds take_snapshot method to compute model.
The functions list_snapshot and revert to snapshot will follow in the future.
Best regards
ireznice
=> [vsphere] add support for taking snapshot

lib/fog/digitalocean/requests/compute_v2/create_ssh_key.rb
The Digital Ocean V2 API returns a 201 on success when creating an ssh key, not a 202: https://developers.digitalocean.com/documentation/v2/#create-a-new-key
I've verified this works locally.  Currently, fog throws an excon exception upon successful creation of an ssh key
=> Fix Digital Ocean V2 ssh key creation

lib/fog/rackspace/requests/load_balancers/create_node.rb, tests/rackspace/requests/load_balancers/node_tests.rb
Fixed bug building the node type request. I also added a test for setting the node type.
I run into this issue trying to set a failover node:
https://community.rackspace.com/products/f/25/t/4377
=> [Rackspace] Fix set node type for Rackspace load balancer

lib/fog/openstack/core.rb
As mentioned in #3744 the "Multiple regions available choose one of these" exception could be raised even when there is only one region.
This happened as the check was performed directly on the array of endpoints, which might include more than one.
=> Fixed issue with OpenStack Auth v2

fog.gemspec
Version for fog-aliyun has been added in fog.gemspec as all versions of fog-aliyun prior to 0.1.0 have been removed
closes #3763
=> version for fog-aliyun added in fog.gemspec

lib/fog/rackspace/requests/storage/put_container.rb
Ironically the docs mention it, but don't actually enforce no-slashes in a container name.
=> Enforce no slash in container name

lib/fog/openstack/models/identity_v2/user.rb
See http://developer.openstack.org/api-ref-identity-admin-v2.html#admin-createUser
Could I get your eyes on this @dhague ? I see you set the tenant_id as a required param but the API doc insists it's optional.
I have a use-case where it's necessary to initially create a user with no tenant assignment and then allow them to be assigned to tenants on request of the user afterwards.
=> [OpenStack] Users can be created without a tenant ID or password

lib/fog/rackspace/compute_v2.rb, lib/fog/rackspace/docs/compute_v2.md, lib/fog/rackspace/models/compute_v2/server.rb, lib/fog/rackspace/requests/compute_v2/get_vnc_console.rb, tests/rackspace/requests/compute_v2/server_tests.rb
Add support for `get_vnc_console` to the Rackspace provider. `get_vnc_console` returns a URL to a HTML5 based VNC client.
Rackspace documentation: https://developer.rackspace.com/docs/cloud-servers/v2/developer-guide/#get-console
```server.get_vnc_console('novnc') => "https://dfw.servers.console.rackspacecloud.com:443/console?token=b40c6057-4bcb-4ee7-a359-dcecc752b379"```
Note: These URLs expire with inactivity.
This is basically a copy of OpenStack's support to the Rackspace provider.
=> [rackspace] Add support for get_vnc_console request to compute_v2

lib/fog/digitalocean/requests/compute_v2/delete_ssh_key.rb
The current path is incorrect (missing a '/'), resulting in a 404 whenever you try to destroy an SSH key on DigitalOcean V2.
=> Update API path for deleting SSH keys

lib/fog/openstack/core.rb
If the management URL has no path, use the one in the auth URI.
This is something of a bandaid solution until a more long term solution is committed. I'll be leaving that in the capable hands of @dhague 
The underlying motivation here is that OpenStack recommend you use management endpoints that don't hard code the API version within it. This causes the `@path` variable to be empty, and so subsequent requests end up going to the wrong place and generating 404s. See the excon debug log below.
```
/Users/sean/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/excon-0.45.4/lib/excon/middlewares/expects.rb:6:in `response_call': Expected(200) <=> Actual(404 Not Found) (Fog::Identity::OpenStack::NotFound)
excon.error.request
:chunk_size          => 1048576
:ciphers             => …
```
=> Fix for setups where Keystone v2 and v3 are both available

lib/fog/openstack/core.rb
This reverts commit f17419049162a582268e0bace3edd4fdc17527d4.
Seems to cause some issues elsewhere in the code not caught by the current test suite but emerging from staging tests.
=> Revert "If the management URL has no path, use the one in the auth URI."

lib/fog/openstack/compute.rb, lib/fog/openstack/core.rb, lib/fog/openstack/identity_v2.rb, lib/fog/openstack/identity_v3.rb, lib/fog/openstack/image_v1.rb, lib/fog/openstack/image_v2.rb, lib/fog/openstack/metering.rb, lib/fog/openstack/network.rb, lib/fog/openstack/orchestration.rb, lib/fog/openstack/planning.rb, lib/fog/openstack/storage.rb, lib/fog/openstack/volume.rb
Introduces a new optional parameter for OpenStack.
```ruby
openstack_identity_prefix: "v2.0"
```
This gets inserted wholesale into calls to the identity service (not including the original token request).
On systems where Keystone v2 is left in for compatibility in addition to Keystone v3 being present, it is recommended to remove the API version from the identity endpoints in Keystone's database. This means the client is then responsible for selecting which version of the API to use.
Since Keystone returns `host:5000/`, it's up to the client to add on `v2.0` or `v3`.
If left blank, the identity URL returned by Keystone's service catalogue is used unmodified. If you need to select between v2 and v3 then set it as above.
=> [openstack] Workaround for installs using both Keystone v2 and v3.

lib/fog/openstack/storage.rb
Hello guys, I noticed a warning when using ```:openstack_temp_url_key``` option for OpenStack storage which doesn't make much sense:
```
2015-12-18_08:11:07.54954 [fog][WARNING] Unrecognized arguments: openstack_temp_url_key
```
when in reality code still uses it and it is perfectly valid. See https://github.com/fog/fog/blob/master/lib/fog/openstack/requests/storage/get_object_https_url.rb#L39, https://github.com/fog/fog/blob/master/lib/fog/openstack/requests/storage/get_object_https_url.rb#L56.
I just whitelisted it as a recognized one. Please have a look and let me know if you have any questions.
Thanks!
=> Add openstack_temp_url_key to the list of recognized options

lib/fog/vcloud_director/compute.rb, lib/fog/vcloud_director/models/compute/vm.rb, lib/fog/vcloud_director/parsers/compute/vm.rb, lib/fog/vcloud_director/parsers/compute/vms.rb, lib/fog/vcloud_director/requests/compute/post_reconfigure_vm.rb
Sorry for raising a PR with two purposes here, but they're quite entwined in my fork.
1. Adds support for reading the `Description` property of VMs.
2. Adds some minimal support for the all-encompassing `reconfigureVm` method of the vCloud Director API. Specifically, you can use the `vm.reconfigure` method to set the following properties:
* `name`
* `cpu`
* `memory`
* `description`
[I know there is already support for PUT `cpu` and PUT `memory` but this method allows people to set them both (and other properties) simultaneously so it's a bit faster. The other two properties previously had no way of being edited in Fog.]
=> vCloud Director: Add support for reconfigureVm and a VM's description

lib/fog/vcloud_director/compute.rb, lib/fog/vcloud_director/requests/compute/delete_vapp.rb, lib/fog/vcloud_director/requests/compute/get_catalog.rb, lib/fog/vcloud_director/requests/compute/get_catalog_item.rb, lib/fog/vcloud_director/requests/compute/get_metadata.rb, lib/fog/vcloud_director/requests/compute/get_vapp.rb, lib/fog/vcloud_director/requests/compute/get_vm.rb, lib/fog/vcloud_director/requests/compute/get_vm_disks.rb, lib/fog/vcloud_director/requests/compute/get_vm_network.rb, lib/fog/vcloud_director/requests/compute/get_vms.rb, lib/fog/vcloud_director/requests/compute/instantiate_vapp_template.rb, lib/fog/vcloud_director/requests/compute/post_power_on_vapp.rb, lib/fog/vcloud_director/requests/compute/post_update_vapp_metadata.rb, lib/fog/vcloud_director/requests/compute/put_network_connection_system_section_vapp.rb
This pull request adds a lot more mocks to the vcloud_director provider.
Specifically, it adds mocks for:
* delete_vapp
* get_catalog
* get_catalog_item
* get_metadata
* get_vapp
* get_vm
* get_vm_disks
* get_vm_network
* get_vms
* post_instantiate_vapp_template
* post_power_on_vapp
* post_update_vapp_metadata
* put_network_connection_system_section_vapp
And fixes a bug in the get_vm_network mock (it was not pulling out the VM ID correctly from the href - I changed the code to match the 'real' parser).
=> vCloud Director: Add lots more mocks

lib/fog/vcloud_director/models/compute/networks.rb, lib/fog/vcloud_director/models/compute/vdc.rb
As well as `org.networks` which gets all the networks in an organization, it is useful to have `vdc.networks` that only gets the networks relevant to a specific virtual DC.
=> [vcloud_director] Add vdc.networks

lib/fog/vcloud_director/models/compute/disks.rb
The standard behaviour of `vm.disks` returns all disk hardware including SCSI/IDE controllers.
This tiny PR adds a `vm.disks.storage_only` that returns only those disks that have a resource type of 17 (indicating that they're actually disks and not controllers).
=> vCloud Director: Add a #storage_only to disks

lib/fog/digitalocean/models/compute_v2/images.rb, lib/fog/digitalocean/requests/compute_v2/list_images.rb
* Added filtering hash to list_images request.
* Appended filter query to list images request url
* Passed existing filtering hash from all method at images collection model to the request call.
Current query does not show all available images. In addition the **all** method at the images does not pass the filters param to the request query. The behavior of the method differs from the API one since it's just the default call.
=> [DigitalOcean] Added filtering capabilities to images request.

lib/fog/openstack/models/image_v2/images.rb
- fix what most probably is a copy paste error evolving from v1
- v2 only has the `list_images` request that accepts hash arguments only
=> [OpenStack] image v2 correct images find_by_* and find_attribute

lib/fog/digitalocean/compute_v2.rb, lib/fog/digitalocean/requests/compute_v2/destroy_server.rb
Ref #3803 
Use destroy_server to maintain consistent destroy api.
=> Deprecate delete_server for destroy_server

lib/fog/openstack/core.rb
Same as in [line 307](https://github.com/MaPoCaCe/fog/blob/9589cad1c6332427415fb91ca49e8ae8af732c5b/lib/fog/openstack/core.rb#L307) the options should be passed to the service retrieval.
FYI: I stumbled upon this, when I needed the option `openstack_endpoint_path_matches` passed to select the correct identity version.
=> [OpenStack] service retrieval also pass options on unscoped fallback

lib/fog/openstack/storage.rb
- same as with all the other services `openstack_api_key` and `openstack_username` are not required
- enables using the `openstack_auth_token`
=> [openstack] storage does not require api_key and username

lib/fog/openstack/identity_v2.rb, lib/fog/openstack/identity_v3.rb
The management calls need the correct prefix prepending to all endpoints for systems that use Keystone v2 and v3. In these setups, the endpoint URLS are set up without the version so Keystone advertises them as
`https://yourserver.com:5000/` or `https://yourserver.com:35357`
instead of
`https://yourserver.com:5000/v2.0` or `https://yourserver.com:35357/v3/`.
This means that all keystone calls in future i.e. list users, domains, create roles etc etc will occur on the version of the API specified by the prefix.
```ruby
openstack_identity_prefix: 'v3'
```
```
Listing domains for Keystone v3:
/v3/domains
```
or
```ruby
openstack_identity_prefix: 'v2.0'
```
```
Listing users for Keystone v2:
/v2.0/users
```
=> [openstack] Supporting installs that expose both keystone v2 and v3

lib/fog/vcloud_director/compute.rb
Excon by default adds the default port to the host header for each request
e.g hostname.example.com:443
Some Cloud Providers use filter rules on HAProxy or similar to control API paths to different backends. In our case the ruleset required will increase if we need to filter for port number as well as host headers where this is not specified. 
rfc2616 specifies that the port number should be appended to the host header if it is not the default port. However, 443 IS the default port for https (as specified in rfc2818) Although I accept that this could be seen as ambiguous given that the rfc2818 refers to HTTP over TLS rather than HTTP as defined in rfc2616.
Basically what I'm trying to say (in a long winded rounadbout way..) is should we make ":omit_default_port" (as supported by Excon) …
=> Strip port number from host header

lib/fog/digitalocean/models/compute_v2/servers.rb, lib/fog/digitalocean/requests/compute_v2/list_servers.rb
#3777 in the same way images were updated to support filtering, here's the same update for servers.
=> [DigitalOcean] Added filtering capabilities to servers request.

lib/fog/openstack/compute.rb, lib/fog/openstack/requests/compute/get_server_password.rb
I added the get_server_password functionality to get the password of the instances from openstack Compute API v2.1
=> [openstack] Add get_server_password support to openstack compute API

lib/fog/openstack/requests/baremetal/set_node_maintenance.rb, lib/fog/openstack/requests/baremetal/unset_node_maintenance.rb, lib/fog/openstack/requests/compute/list_services.rb
which causes NoMethodError in ruby's uri/rfc2396_parser.rb
when passed parameter's value is ie. Fixnum.
=> [openstack] Removes URI::encode call on parameteres

lib/fog/digitalocean/compute_v2.rb
If you're just loading fog/digitalocean in your application and some
request fails, no logs will be provided. Instead an error 'uninitialized
constant Fog::Compute::Bluebox' will show up. This is because for some
reason DO calls Bluebox::NotFound when a request fails.
=> [DigitalOcean] - Failed requests fail to log because of Bluebox

lib/fog/digitalocean/models/compute_v2/server.rb
It seems that every other plugin expect `:state` for instance, https://github.com/fog/fog/blob/master/lib/fog/openstack/models/compute/server.rb#L34. DO needs to have the alias of `:state` to `:status` to help some down stream usage. 
Consistancy is the key to happiness :)
=> Standardize the `:state` alias to `:status`

lib/fog/openstack/models/network/floating_ip.rb, lib/fog/openstack/network.rb, lib/fog/openstack/requests/network/associate_floating_ip.rb, lib/fog/openstack/requests/network/create_floating_ip.rb, lib/fog/openstack/requests/network/disassociate_floating_ip.rb, lib/fog/openstack/requests/network/get_floating_ip.rb
- added `associate` and `disassociate` into floating_ip objet
- make mock requests concern `floating_ip` to have same behaviors as compute's
=> rework floating_ip object

lib/fog/vcloud_director/parsers/compute/vm_customization.rb
The AdminPassword XML element isn't present unless AdminPasswordEnabled but the API on the other end expects it to be set.
=> [vcloud_director] Fix VM Customization 400 

lib/fog/vcloud_director/requests/compute/put_product_sections.rb
The current method for setting GuestProperties on vApps & VMs does not set the <ovf:Label> tag. 
this means that via vCloud Director UI Guest Property Key names are not shown, only values.
I've added the tag and tested.
=> Added label to Guest Properties

fog.gemspec
`fog-aliyun` was at the bottom of the list when it should be at the top,
per the comment.
=> Keeping the dependency gems in order

lib/fog/fogdocker/requests/compute/container_action.rb
Errors don't have an "Error" namespace so we're getting unintialized constant exceptions. See https://github.com/fog/fog-core/blob/d18398c44e9e8d57025874ed43a573434dbd0f95/lib/fog/core/errors.rb.
=> [docker] Fixing bad namespace on errors

lib/fog/digitalocean/models/compute_v2/ssh_keys.rb
- There needs to be no filter with the all method call.
- Removed an extra WS
=> Removed 'filters' from ssh_key all method

README.md, fog.gemspec
Adding a simple postinstall message + README section to tell users not to use
fog gem if they require only specific dependencies.
Here's how it looks like:
```
λ gem install --local ./fog-1.38.0.gem                                                                                                                                                                                     (1)
------------------------------
Thank you for installing fog!
IMPORTANT NOTICE:
If there's a metagem available for your cloud provider, e.g. `fog-aws`,
you should be using it instead of requiring the full fog collection to avoid
unnecessary dependencies.
'fog' should be required explicitly only if:
- The provider you use doesn't yet have a metagem available.
- You require Ruby 1.9.3 support. …
```
=> Adding postinstall message

lib/fog/vcloud_director/compute.rb, lib/fog/vcloud_director/generators/compute/create_snapshot.rb, lib/fog/vcloud_director/requests/compute/post_create_snapshot.rb
I added two classes:
- lib/fog/vcloud_director/generators/compute/create_snapshot.rb
- lib/fog/vcloud_director/requests/compute/post_create_snapshot.rb
I also added the reference of the request in lib/fog/vcloud_director/compute.rb
=> Vcloud-director create-snapshot for vm/vapp

lib/fog/digitalocean/models/compute_v2/flavors.rb, lib/fog/digitalocean/models/compute_v2/ssh_keys.rb, lib/fog/digitalocean/requests/compute_v2/list_flavors.rb, lib/fog/digitalocean/requests/compute_v2/list_servers.rb, lib/fog/digitalocean/requests/compute_v2/list_ssh_keys.rb, tests/digitalocean/requests/compute_v2/list_ssh_keys_tests.rb
Fixes the filtering for the `list_ssh_keys`, and `list_flavors` requests. Also fixes tests for `list_servers` to pass again and add tests for `list_ssh_keys`.
=> Digital Ocean request filtering fixes & test fixes 

lib/fog/digitalocean/requests/compute_v2/list_flavors.rb, lib/fog/digitalocean/requests/compute_v2/list_images.rb, lib/fog/digitalocean/requests/compute_v2/list_regions.rb, lib/fog/digitalocean/requests/compute_v2/list_servers.rb, lib/fog/digitalocean/requests/compute_v2/list_ssh_keys.rb
Use Excon’s query parameter handling and escaping rather
than doing it manually.
=> Digital Ocean list_* requests pass query params to Excon

lib/fog/cloudsigma/compute.rb, lib/fog/cloudsigma/models/server.rb, lib/fog/cloudsigma/models/snapshot.rb, lib/fog/cloudsigma/models/snapshots.rb, lib/fog/cloudsigma/models/volume.rb, lib/fog/cloudsigma/requests/clone_snapshot.rb, lib/fog/cloudsigma/requests/create_snapshot.rb, lib/fog/cloudsigma/requests/delete_snapshot.rb, lib/fog/cloudsigma/requests/get_snapshot.rb, lib/fog/cloudsigma/requests/list_snapshots.rb, lib/fog/cloudsigma/requests/stop_server.rb, lib/fog/cloudsigma/requests/update_snapshot.rb, tests/cloudsigma/models/snapshot_tests.rb, tests/cloudsigma/models/snapshots_tests.rb, tests/cloudsigma/models/volume_tests.rb, tests/cloudsigma/requests/server_tests.rb, tests/cloudsigma/requests/snapshots_tests.rb, tests/cloudsigma/requests/volumes_tests.rb
Added snapshots to compute model for CloudSigma provider. Snapshots are point-in-time versions of a drive. They can be cloned (promoted) to a full drive. [Official API docs] (https://cloudsigma-docs.readthedocs.org/en/latest/snapshots.html).
=> [CloudSigma] add snapshots

lib/fog/cloudstack/core.rb
In general, any requests with a asterisk (*) character is malformed.
The deep rooted reason is that at cloudstack core, CGI escape is used. As of HTTP specification, we should be using URI escape instead.
=> Use URI escape instead of CGI escape as of HTTP specification

lib/fog/opennebula/requests/compute/vm_allocate.rb
>...
INFO fog: compute!
"CPU=1\nVCPU=12\nMEMORY=16384\nDISK=[\"DRIVER\"=\"qcow2\", \"IMAGE_ID\"=\"206\"]\nNIC=[MODEL=\"\",NETWORK_ID=\"13\"]\nOS=[\"ARCH\"=\"x86_64\", \"BOOT\"=\"hd\"]\nGRAPHICS=[\"LISTEN\"=\"192.168.0.4\", \"PORT\"=\"5602\", \"TYPE\"=\"spice\"]\nRAW=[\"DATA\"=\"<devices>   <memballoon model='virtio'/> </devices> <memory unit='MiB'>16384</memory> <currentMemory unit='MiB'>2048</currentMemory>\", \"TYPE\"=\"kvm\"]\n\n\nNAME=My Team - Virtual Machine [Web] [Ubuntu]"
ERROR warden: Error occurred: [VirtualMachineAllocate] Error allocating a new virtual machine. Parse error: syntax error, unexpected VARIABLE, expecting EQUAL or EQUAL_EMPTY at line 11, columns 382:387
...
I just dumped the XML sent to OpenNebula to show that it doesn't escape the VM name.
=> #3900 Escape VM name in OpenNebula allocator

Gemfile, fog.gemspec
First pass at fixing dependencies.
We really-really should think about dropping 1.9 sooner.
=> Fixing gemspec conflicts with 1.9

fog.gemspec, lib/fog/ovirt/compute.rb, lib/fog/ovirt/models/compute/instance_type.rb, lib/fog/ovirt/models/compute/instance_types.rb, lib/fog/ovirt/models/compute/server.rb, lib/fog/ovirt/requests/compute/get_instance_type.rb, lib/fog/ovirt/requests/compute/list_instance_types.rb, lib/fog/ovirt/requests/compute/mock_files/instance_type.xml, lib/fog/ovirt/requests/compute/mock_files/instance_types.xml
Add instance_types support to oVirt provider. Depends on https://github.com/abenari/rbovirt/pull/117 merged today, but not released ATM.
=> Add instance_types support to oVirt provider

lib/fog/ovirt/models/compute/server.rb
This is to be able to pass `disks` and `clone` to become a part of the xml created here: https://github.com/abenari/rbovirt/blob/master/lib/ovirt/vm.rb#L111-L117
See comment: https://github.com/theforeman/foreman/pull/4512#issuecomment-301305759
=> [ovirt] adding disks and clone to attribute

lib/fog/ovirt/models/compute/server.rb
When stopping and starting as part of the reboot, it can happen the VM
stopping is not finished before starting, leading to getting this error
in oVirt:
[Operation Failed: [Cannot run VM because the VM is in Powering Down status.]
=> [ovirt] wait for stopped before starting when rebooting

lib/fog/vcloud_director/requests/compute/post_power_on_vapp.rb, lib/tasks/changelog_task.rb, lib/tasks/github_release_task.rb
This PR suppresses the following warning.
``` ruby
ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
RUBYOPT=-w bundle exec rake  
/fog/lib/tasks/changelog_task.rb:180: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/fog/lib/tasks/github_release_task.rb:50: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/fog/lib/fog/vcloud_director/requests/compute/post_power_on_vapp.rb:68: warning: mismatched indentations at 'end' with 'class' at 34
```
=> Suppress warning

fog.gemspec
The README states
> Fog requires Ruby 2.0.0 or later.
and `json` 2.0 should thus now work properly.
(Also see #3707, which removed Ruby 1.9.3 support.)
=> Upgrade JSON to ~> 2.0

lib/fog/vcloud_director/compute.rb, lib/fog/vcloud_director/generators/compute/network_config_section.rb, lib/fog/vcloud_director/requests/compute/instantiate_vapp_template.rb, lib/fog/vcloud_director/requests/compute/put_config_network_section_vapp.rb
- if we don't want to pass a network while the instantiation we have to make this field optionnal
- implement the put api to configure the network section in vapp
=> make network optionnal for instantiate request

fog.gemspec
Now that we have released 2.0.0, and are no longer supporting ruby-1.9.3, fog-google and mime-types can be unpinned. mime-types 3.0 dropped ruby-1.9.3 support, as did fog-google at v0.1.1.
=> Upgrade fog-google and mime-types

lib/fog/cloudstack/models/compute/server.rb
Similar to https://github.com/fog/fog/pull/3566
Not only the size of DATADISK, but also I would like to specify the size of root disk for cloudstack.
http://cloudstack.apache.org/docs/api/apidocs-4.4/root_admin/deployVirtualMachine.html
=> [cloudstack] Allow specifying the size of root volume

lib/fog/opennebula/compute.rb, lib/fog/opennebula/requests/compute/OpenNebulaVNC.rb, spec/fog/compute_spec.rb, tests/cloudsigma/models/snapshot_tests.rb, tests/cloudsigma/models/snapshots_tests.rb, tests/cloudsigma/requests/snapshots_tests.rb, tests/cloudsigma/requests/volumes_tests.rb, tests/opennebula/compute_tests.rb, tests/opennebula/models/compute/flavor_tests.rb, tests/opennebula/models/compute/flavors_tests.rb, tests/opennebula/models/compute/group_tests.rb, tests/opennebula/models/compute/groups_tests.rb, tests/opennebula/models/compute/network_tests.rb, tests/opennebula/models/compute/networks_tests.rb, tests/opennebula/requests/compute/vm_allocate_tests.rb, tests/opennebula/requests/compute/vm_suspend_resume_tests.rb
Hi guys,
I've dug into the errors I'm seeing on Travis and seem to have isolated
workarounds for the bulk of them.
This is still blocked by https://github.com/fog/fog-aliyun/pull/20 however
but there is a fix for that as well.
Individual commits should have details for each change that was needed
and the reasoning.
Ideally for the `opennebula` changes, there would be a `fog-core` error covering
"missing/optional by provider" dependencies rather than just `LoadError` so it
is clearer what the issue is.
It was only after digging into the "OpenNebula does not have a compute service"
problem did I realise `fog-core`'s `LoadError` handling was hiding a reference to
`xmlrpc` which was leaking from any call to `Fog::Compute[:opennebula]`
However, I didn't want to add an update to fog-core in …
=> Fix main Travis issues

spec/fog/bin/atmos_spec.rb, spec/fog/bin/aws_spec.rb, spec/fog/bin/baremetalcloud_spec.rb, spec/fog/bin/bluebox_spec.rb, tests/cloudstack/compute/models/volume_tests.rb
This fixes a number of references to deprecated methods or classes.
The main bulk is removing the tests for the Fog "binary" that allowed providers to call their services directly from the top level, e.g. `Brightbox[:compute]`
These tests would flood the testing output with deprecation warnings when no one will hopefully be using that interface anymore.
It also fixes a reference to `#connection` which should be `#service`.
The warnings have disappeared on Travis but there are still plenty more.
=> Fix deprecation warning appearing in tests

fog.gemspec
I've mentioned this before but the gist is - due to unexpected `resourceviews` API deprecation <=0.1.X versions of `fog-google` no longer load. Problem is fog-1.X is the last version to support Ruby 1.9, so it would be good to provide a `1.43` for legacy users with the hotfix.
However, I do understand that it's somewhat complicated to release a legacy version so if you think this is too much hassle - no worries - just let me know.
Targeting release-1.42.0 branch.
For more info on why this happened see https://github.com/fog/fog-google/commit/3ba154554382d9cfe9f29710795ec638be881260
=> Hotfix bump needed for fog-google in fog-1.X

fog.gemspec
This reduces unneeded redirection from `http://...` to `https://...` when someone visits this gem's homepage via https://rubygems.org/gems/fog.
=> GitHub is https by default

lib/fog/linode/requests/compute/avail_datacenters.rb
It would appear that the existing test cases should suffice for providing coverage: https://github.com/fog/fog/blob/master/tests/linode/requests/compute/datacenter_tests.rb
=> lib/fog/linode: Add Tokyo2 to avail_datacenters

lib/fog/bin/brightbox.rb, spec/fog/bin/brightbox_spec.rb
fog-brightbox updated namespaces into Fog::Brightbox format.
I am not sure if this is compatible with older fog-brightbox, which is now demanded by fog, but I guess I'll know soon :)
=> Fix compatibility with fog-brightbox 1.0.0+.

Rakefile, fog.gemspec
The RubyGems property rubyforge_project is removed without a replacement.
=> Gemspec: Drop EOL'd property rubyforge_project

fog.gemspec
https://www.ruby-lang.org/en/news/2020/03/19/json-dos-cve-2020-10663/
Upgreade json gem version
=> json-dos-cve-2020-10663

.github/workflows/ruby.yml, fog.gemspec
Ruby 2.0 is EOL, supported Ruby versions are 2.6+ and currentl Rubocop supports 2.4+. This is a good compromise.
=> Supported Ruby version is 2.5+ now

.github/workflows/ruby.yml, .github/workflows/stale.yml
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>
=> Set permissions for GitHub actions
